---
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - eslint-config-prettier
rules:
  "@typescript-eslint/ban-ts-comment":
    - off
  no-unused-vars:
    - warn
  "@typescript-eslint/member-delimiter-style":
    - warn
    -
      multiline:
        delimiter: none
